title: Aliucord plugin library
description: An unoffical Aliucord plugin library webpage!
theme: just-the-docs
color_scheme: dark

url: https://aliucord-plugins.github.io/

aux_links:
  "Github source": "https://github.com/aliucord-plugins/aliucord-plugins.github.io"
